djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('staff.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

staff/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('tree/', views.home, name="home"),
    path('list/', views.list, name="list"),
]

staff/models.py
from django.db import models


class Employee(models.Model):
    full_name = models.CharField(max_length=255)
    position = models.CharField(max_length=255)
    employed_at = models.DateTimeField()
    chief = models.ForeignKey('self', on_delete=models.CASCADE, null=True)

    root = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_ad = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Employee'
        verbose_name_plural = 'Employees'

    def __str__(self):
        return self.full_name[:2]

    def save(self, *args, **kwargs):
        if Employee.objects.count() == 0:
            self.root = True
            self.chief = None
            super(Employee, self).save(*args, **kwargs)
        elif self.chief is not None:
            super(Employee, self).save(*args, **kwargs)

staff/forms.py
from django import forms


class SearchForm(forms.Form):
    input = forms.CharField(max_length=255)

staff/views.py
from django.contrib.postgres.search import SearchVector
from django.db.models import Q
from django.shortcuts import render
from .models import Employee
from .forms import SearchForm


def home(request):
    employees = Employee.objects.all()
    return render(request, 'home.html', {"employees": employees, "ceo": employees[0]})


def list(request):
    query = Employee.objects.all()

    sortKey = request.GET.get('sort')
    searchKey = request.GET.get('search')

    if sortKey is not None and sortKey in [f.name for f in Employee._meta.fields]:
        query.order_by(sortKey)

    if searchKey is not None:
        query.filter(
            Q(full_name__icontains=searchKey) | Q(position__icontains=searchKey) | Q(full_name__contains=searchKey) | Q(
                position__contains=searchKey)
        )
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            inp = form.cleaned_data['input']
            employees = Employee.objects.filter(
                Q(full_name__icontains=inp) | Q(position__icontains=inp) | Q(full_name__contains=inp) | Q(
                    position__contains=inp)
            )
            return render(request, 'sort.html', {"employees": employees, "form": form})
    else:
        form = SearchForm()
    return render(request, 'sort.html', {"employees": query, "form": form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Staff</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<style>
    /* Remove default bullets */
ul, #myUL {
  list-style-type: none;
}

/* Remove margins and padding from the parent ul */
#myUL {
  margin: 0;
  padding: 0;
}

/* Style the caret/arrow */
.caret {
  cursor: pointer;
  user-select: none; /* Prevent text selection */
}

/* Create the caret/arrow with a unicode, and style it */
.caret::before {
  content: "\25B6";
  color: black;
  display: inline-block;
  margin-right: 6px;
}

/* Rotate the caret/arrow icon when clicked on (using JavaScript) */
.caret-down::before {
  transform: rotate(90deg);
}

/* Hide the nested list */
.nested {
  display: none;
}

/* Show the nested list when the user clicks on the caret/arrow (with JavaScript) */
.active {
  display: block;
}
</style>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Staff</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'list' %}">Sort</a>
        </li>

      </ul>
      <form class="d-flex search-form" method="POST">
          {% csrf_token %}
          {{form.field.as_hidden}}
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</body>
</html>

templates/home.html
{% include 'base.html' %}
{% block content %}

    <ul id="myUL">
        <li><span class="caret">{{ ceo.full_name|slice:"0:20" }}</span>
        {% include "menu.html"  with menu_list=ceo %}
    </ul>

    <script>
    var toggler = document.getElementsByClassName("caret");
var i;

for (i = 0; i < toggler.length; i++) {
  toggler[i].addEventListener("click", function() {
    this.parentElement.querySelector(".nested").classList.toggle("active");
    this.classList.toggle("caret-down");
  });
}
</script>
{% endblock %}

templates/menu.html
 <ul class="nested">
{% for menu in menu_list.employee_set.all %}



        {% if menu.employee_set.all|length %}
            <li><span class="caret">{{ menu.full_name|slice:"0:20" }}</span>
            <ul>
                {% include "menu.html" with menu_list=menu %}
            </ul>
        {% else %}
            <li>{{ menu.full_name|slice:"0:20" }}</li>
        {% endif %}


{% endfor %}
</ul>

templates/sort.html
{% include  'base.html'%}
<ul>
    {% for employee in employees %}
        <li>{{ employee.full_name|slice:"0:20" }} | {{ employee.position|slice:"0:20" }} | {{ employee.employed_at }} | {{ employee.chief.full_name|slice:"0:20"}}</li>
    {% endfor %}
</ul>